---
name: CI

'on':
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container: ${{ matrix.container }}

    strategy:
      matrix:
        container:
          - debian:jessie
          - debian:stretch
          - debian:bullseye
          - debian:latest
          - ubuntu:trusty
          - ubuntu:xenial
          - ubuntu:bionic
          - ubuntu:latest
          - centos:6
          - centos:7
          - centos:8
          - centos:latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: |

      - name: Run installer script
        run: ./install.sh -d

      - name: Run installer script (stdin)
        run: curl -s file://$PWD/install.sh | bash -s -- -d
