---
name: CI

'on':
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test on ${{matrix.image }}
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        env:
          # - image: debian:jessie
          #   tag: debian-jessie
          #   dockerfile: Dockerfile-debian
          # - image: debian:latest
          #   tag: debian-latest
          #   dockerfile: Dockerfile-debian
          # - image: ubuntu:xenial
          #   tag: ubuntu-xenial
          #   dockerfile: Dockerfile-debian
          - image: ubuntu:latest
            tag: ubuntu-latest
            dockerfile: Dockerfile-debian
          # - image: centos:7
          #   tag: centos-7
          #   dockerfile: Dockerfile-centos
          # - image: centos:latest
          #   tag: centos-latest
          #   dockerfile: Dockerfile-centos

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          cp .github/docker/${{ matrix.dockerfile }} Dockerfile
          sed -i 's/@@IMAGE@@/${{ matrix.image }}/g' Dockerfile

      - name: Run installer script
        uses: ./
