---
name: CI

'on':
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - label: Debian (8)
            image: debian:jessie
            file: Dockerfile-debian

          - label: Debian (latest)
            image: debian:latest
            file: Dockerfile-debian

          - label: Ubuntu (16.04)
            image: ubuntu:xenial
            file: Dockerfile-debian

          - label: Ubuntu (18.04)
            image: ubuntu:bionic
            file: Dockerfile-debian

          - label: Ubuntu (latest)
            image: ubuntu:latest
            file: Dockerfile-debian

          - label: CentOS (7)
            image: centos:7
            file: Dockerfile-redhat
          
          - label: CentOS (8)
            image: centos:8
            file: Dockerfile-redhat

          - label: CentOS (latest)
            image: centos:latest
            file: Dockerfile-redhat

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          cp .github/docker/${{ matrix.file }} Dockerfile
          sed -i 's/@@IMAGE@@/${{ matrix.image }}/g' Dockerfile

      - name: Run installer script
        uses: ./
        with:
          entrypoint: /entrypoint-local.sh

      - name: Run installer script (headless)
        uses: ./
        with:
          entrypoint: /entrypoint-remote.sh
